language: node_js
matrix:
  include:
    - node_js: 6.14.0
    - node_js: 6.14.0
      env: SAUCE=true
    - node_js: 6.14.0
      env: INTEGRATION=true
script:
  - |
    echo "machine github.com login stellar-jenkins password $GITHUB_TOKEN" >~/.netrc
    git config --global user.name "Travis CI"
    git config --global user.email "travis@stellar.org"
    if [ "${SAUCE}" = "true" ]; then
      if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then
        gulp test:sauce
      else
        echo "Pull request - skip Sauce Labs testing..."
      fi
    elif [ "${INTEGRATION}" = "true" ]; then
      # Ugly but it's the only way to make istanbul generate coverage report
      gulp test:integration
    else
      gulp test:unit
    fi
after_success:
  - |
    # Send report to coveralls but only once
    if [ "${INTEGRATION}" = "true" ] && [ "${TRAVIS_BRANCH}" = "master" ] ; then
      gulp submit-coverage
    fi
env:
  global:
    - secure: Pc3DwkXywnOGAhUdBZiUCKjyljzrQzPoqm9EEr+UL2BaeaDniFLCLEkuU+ViiuJBo8oPyOIl7I+d86Mi5q06fQx55+xH7DmiW/aj4qKVB2U6Ghn6A3QWkQuvRB1o8SP7iTYRCX480ULZs6AGrMd9y1PFRx/L93fBrO+J/bOtEmg=
notifications:
  slack:
    secure: CgXxNEQrQ82EatyF/wSdF0P5rXcWPL+fFZ1lb1aBb8RbVt5gwddJ6xWVD/nYSr6tIJvIYHYhoYsIDPENwezIPsesG7kWXerQhydsEcA34JKxzsStd/TmU6Moxuwy6KTN7yzmL6586nSvoAw9TNPgvRkJFkH07asjGIc9Rlaq7/Y=
before_deploy: gulp build
after_deploy: './after_deploy.sh'
deploy:
  - provider: npm
    email: npm@stellar.org
    api_key:
      secure: R5cgAyJp+dNkAFXRQ2qAHPXsvnAx8bKVj/JiwyQyVEcjNMCZTZpGXoUg8woBBybUdY/wtleZf0uowMgA006PVI3SCVdXK7G6SziU2Kixur9de+Xo3kNKiEaPm3ZDprkWSX936dDiA9p1Kh6KuICUBimai/qa3J71U7YFO+pMqwIlqJ/6z7VbJdh8n1xOJvTkwha7yq2ZUoYqLmjU5Vakw6Fg63bTnJVyPS1V9N+auyVxKCxhLFDxKUyteS6lTc45i+5rxtttza9f+xVT0SzYV6B8uQobCCOynA4W3LdoLqAbChTUKVES/kWrQVbFRl2G/ibXt+6Mms6BsLlllcTjrH5rJlJSpGDgrDocOyPE5jVHoH94Kd/3UnbEjUWFQWDRQ7yjFHVox3XVHP6ugQrKiwv82+XE7eHM1a1JniYVkSiW21yntuqx3r4XcpAZBppcSjZv50ZVdgHyeMTCKlBWLXDgIivRHr4oYDIs3+Pv/YM3OhgbgpDawq+87UOOeEdy5rdHsQzzRlk8HZkruwcMUqvwvIx5PFx8KUINg6y7IBwGlig48d/YJ+JMZZKuCVABTqTc9nSYhz8q7BKUxuwmu3kcsntpS125J4Wp3BPv454HdcmxJyH2goNTmAyJ0XtnMwnODwdJIEU89D7pOIYcrDnp2hPgMRXVMUDwmlmXeOM=
    skip_cleanup: true
    on:
      tags: true
      repo: stellar/js-stellar-sdk
      node: 6.14.0
      condition: '$INTEGRATION = true'
  - provider: script
    script: './bower_publish.sh'
    skip_cleanup: true
    on:
      tags: true
      repo: stellar/js-stellar-sdk
      node: 6.14.0
      condition: '$INTEGRATION = true'
