name: Tests

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: gulp

      - name: Unit Tests
        run: gulp test:unit

      - name: Browser Tests
        run: gulp test:browser

      - name: Integration Tests
        run: gulp test:integration
